/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moviemaster;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleRole;
import javax.swing.JOptionPane;
import jess.*;
import jess.awt.TextAreaWriter;
/**
 *
 * @author hatem
 */
public class MovieFinder extends javax.swing.JFrame {

    /**
     * Creates new form MovieFinder
     */
    public MovieFinder() {
        initComponents();
        resultat.setText("fff");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acteurbox = new javax.swing.JComboBox();
        genreBox = new javax.swing.JComboBox();
        contenubox = new javax.swing.JComboBox();
        annebox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paysbox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        producteurbox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acteurbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hugh Jackman", "Christian Bale", "Shia LaBeouf", "Esther Comar", "Will Smith", "Michael Moore", "Leonardo Dicaprio", "Tom Hanks", "Tobey Maguire", "Leonardo Dicaprio", "Anne Hathaway", "Jude Law", "Robert Downey Jr.", "Robert Downey", "Zach Galifianakis", "Scarlett Johansson", "Jennifer Lawrence", "Tom Cruise", "Treat Williams", "Jesse Eisenberg", "Mark Wahlberg", "Daniel Radcliffe", "Jason Statham", "Harrison Ford", "Henry Cavi", "Macaulay Culkin", "Shia Labeouf", "Brad Pit" }));
        acteurbox.setName("acteur"); // NOI18N
        getContentPane().add(acteurbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 108, -1));

        genreBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fantasy", "Aventure", "Comedie", "Action", "Magie", "Thriller", "Bibliographie", "Science-fiction", "Drame", "Romance", "Documentaire" }));
        genreBox.setName("genre"); // NOI18N
        getContentPane().add(genreBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 135, -1));

        contenubox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "rêve", "banque", "adolescent", "enfant perdu", "Zeus", "espace", "mini cooper", "sorcier", "hospital", "facebook", "samurai", "pearl harbor", "espion", "dans une île", "organe", "voyage", "hero", "robot", "love story", "zombie", "poursuite", "spider", "general motors", "donation", "amour", "magie" }));
        contenubox.setName("contenu"); // NOI18N
        contenubox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenuboxActionPerformed(evt);
            }
        });
        getContentPane().add(contenubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 108, -1));

        annebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1977", "1980", "1989", "1990", "1996", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", " " }));
        annebox.setName("annee"); // NOI18N
        annebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneboxActionPerformed(evt);
            }
        });
        getContentPane().add(annebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 135, -1));

        jLabel1.setText("Acteur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 44, 80, 20));

        jLabel2.setText("Genre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 80, 20));

        jLabel3.setText("Contenu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, 20));

        jLabel4.setText("Anneé");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 90, 20));

        jLabel5.setText("Nom de Film :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 110, 30));

        paysbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USA", "Angleterre", "Japon", "Prage", "Sydney", "Secteur 13", "mer", "France" }));
        paysbox.setName("pays"); // NOI18N
        getContentPane().add(paysbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        jLabel6.setText("Pays");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 70, 30));

        jLabel7.setText("Producteur");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 60, 20));

        producteurbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Christopher Nolan", "D.J. Caruso", "Peter Berg", "Gabriele Muccino", "Michael Moore", "James Cameron", "Steven Spielberg", "Sam Raimi", "Francis Lawrence", "Lone Scherfig", "Chris Brigham", "Jon Favreau", "Joss Whedon", "Todd Phillips", "Michael Bay", "J.J. Abrams", "Brian De Palma", "Chris Columbus", "Edward Zwick", "Jerry Weintraub", "David Leo Fincher", "Robbie Robertson", "David Heyman", "Gianni Nunnari", "Gary Kurtz", "Donald De Line" }));
        producteurbox.setName("producteur"); // NOI18N
        getContentPane().add(producteurbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 140, -1));

        jButton1.setText("Chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, -1));

        resultat.setColumns(20);
        resultat.setRows(5);
        jScrollPane1.setViewportView(resultat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Film f= new Film();
            
            
            f.setActeur(acteurbox.getSelectedItem().toString());
            f.setAnnee(annebox.getSelectedItem().toString());
            f.setContenu(contenubox.getSelectedItem().toString());
            f.setGenre(genreBox.getSelectedItem().toString());
            f.setPays(paysbox.getSelectedItem().toString());
            f.setProducteur(producteurbox.getSelectedItem().toString());
            Rete engine = new Rete();
            
            engine.batch("movie.clp");
            engine.add(f);
            
            
            
          
            engine.run();
            if(f.getNom()==null){
                JOptionPane.showMessageDialog(null,"FILM n'exite pas");
                
            }
            resultat.setText(f.getNom());
            
        } catch (JessException ex) {
            Logger.getLogger(MovieFinder.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contenuboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenuboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contenuboxActionPerformed

    private void anneboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anneboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieFinder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox acteurbox;
    private javax.swing.JComboBox annebox;
    private javax.swing.JComboBox contenubox;
    private javax.swing.JComboBox genreBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox paysbox;
    private javax.swing.JComboBox producteurbox;
    private javax.swing.JTextArea resultat;
    // End of variables declaration//GEN-END:variables
}
